#+TITLE: gRPC-Web with ClojureScript

This should have been easy...but ran into problems.  Most of this is likely my ignorance of how the javascript
world shifted while I was looking at other things.

1. We will design a quick little protocol for a client to get a stream of events.
2. We will generate the javascript for the protocol.
3. We will use that from clojurescript.

* Protocol

 See [[./protos/entityevents.proto]].

#+begin_src 
service EntityMonitor {
  rpc Subscribe() returns (stream EntityEvent);
  }
...
#+end_src 

* Step 2: Build the gRPC communication code

We will need gRPC's [[https://grpc.io/docs/protoc-installation/#install-using-a-package-manager][protoc compiler]].
 
We will also need the grpc web plugin from [[https://github.com/grpc/grpc-web/releases][here]].

#+begin_example
$ grpconcljs-app git:(main) ✗  protoc --version
libprotoc 3.0.0
#+end_example.
I think we are ready to go.

#+begin_src sh
mkdir -p protos.out

protoc protos/entityevents.proto \
  --js_out=import_style=closure:protos.out \
  --grpc-web_out=import_style=closure,mode=grpcwebtext:protos.out 
#+end_src

This generated some javascript.  
- new file:   protos.out/entity.js
- new file:   protos.out/entityevent.js
- new file:   protos.out/entityeventcode.js
- new file:   protos.out/protos/entityevents_grpc_web_pb.js
- new file:   protos.out/subscribereq.js

Hmmm using 3.0.0 may not have bugs worked out.  So downloaded 3.19.4.

#+begin_example
$  grpconcljs-app git:(main)  protoc --version                                
libprotoc 3.19.4

$  grpconcljs-app git:(main) ✗  rm -rfv protos.out/*
zsh: sure you want to delete all 5 files in /home/skelter/work/grpconcljs-app/protos.out [yn]? y
removed 'protos.out/entityeventcode.js'
removed 'protos.out/entityevent.js'
removed 'protos.out/entity.js'
removed 'protos.out/protos/entityevents_grpc_web_pb.js'
removed directory 'protos.out/protos'
removed 'protos.out/subscribereq.js'
$  grpconcljs-app git:(main) ✗  protoc protos/entityevents.proto \
  --js_out=import_style=closure:protos.out \
  --grpc-web_out=import_style=closure,mode=grpcwebtext:protos.out
$  grpconcljs-app git:(main) ✗  git status
On branch main
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   protos.out/entity.js
	modified:   protos.out/entityevent.js
	modified:   protos.out/entityeventcode.js
	modified:   protos.out/subscribereq.js

#+end_example

* Step 3: Use the communication code from CLJS

* Problem: Why can't we find grpc.web.MethodDescriptor
