/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.entityevents.EntityEvent');

goog.require('jspb.Message');
goog.require('proto.entityevents.Entity');

goog.forwardDeclare('proto.entityevents.EntityEventCode');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.entityevents.EntityEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.entityevents.EntityEvent.repeatedFields_, null);
};
goog.inherits(proto.entityevents.EntityEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.entityevents.EntityEvent.displayName = 'proto.entityevents.EntityEvent';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.entityevents.EntityEvent.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.entityevents.EntityEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.entityevents.EntityEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.entityevents.EntityEvent} msg The msg instance to transform.
 * @return {!Object}
 */
proto.entityevents.EntityEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    code: msg.getCode(),
    entityList: jspb.Message.toObjectList(msg.getEntityList(),
    proto.entityevents.Entity.toObject, includeInstance),
    fromid: msg.getFromid(),
    assocattr: msg.getAssocattr(),
    toid: msg.getToid()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.entityevents.EntityEvent} The clone.
 */
proto.entityevents.EntityEvent.prototype.cloneMessage = function() {
  return /** @type {!proto.entityevents.EntityEvent} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional EntityEventCode code = 1;
 * @return {!proto.entityevents.EntityEventCode}
 */
proto.entityevents.EntityEvent.prototype.getCode = function() {
  return /** @type {!proto.entityevents.EntityEventCode} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {!proto.entityevents.EntityEventCode} value  */
proto.entityevents.EntityEvent.prototype.setCode = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * repeated Entity entity = 2;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.entityevents.Entity>}
 */
proto.entityevents.EntityEvent.prototype.getEntityList = function() {
  return /** @type{!Array.<!proto.entityevents.Entity>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.entityevents.Entity, 2));
};


/** @param {Array.<!proto.entityevents.Entity>} value  */
proto.entityevents.EntityEvent.prototype.setEntityList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


proto.entityevents.EntityEvent.prototype.clearEntityList = function() {
  this.setEntityList([]);
};


/**
 * optional string fromId = 3;
 * @return {string}
 */
proto.entityevents.EntityEvent.prototype.getFromid = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 3, ""));
};


/** @param {string} value  */
proto.entityevents.EntityEvent.prototype.setFromid = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string assocAttr = 4;
 * @return {string}
 */
proto.entityevents.EntityEvent.prototype.getAssocattr = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 4, ""));
};


/** @param {string} value  */
proto.entityevents.EntityEvent.prototype.setAssocattr = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional string toId = 5;
 * @return {string}
 */
proto.entityevents.EntityEvent.prototype.getToid = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 5, ""));
};


/** @param {string} value  */
proto.entityevents.EntityEvent.prototype.setToid = function(value) {
  jspb.Message.setField(this, 5, value);
};


